apiVersion: v1
kind: Service
metadata:
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-name: service-fastfood-app
   service.beta.kubernetes.io/aws-load-balancer-type: nlb
   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: service-fastfood-app
  labels:
    app: service-fastfood-app
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - port: 80
    name: service-fastfood-app
    targetPort: 3210
    protocol: TCP
  selector:
    app: fastfood-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-app
  labels:
    app: fastfood-app
spec:
  selector:
    matchLabels:
      app: fastfood-app
  template:
    metadata:
      labels:
        app: fastfood-app
    spec:
      containers:
      - name: fastfood-app
        image: thiagoluis88/fastfood-app:0.0.25
        envFrom:
          - secretRef:
              name: app-env-secret
          - configMapRef:
              name: cm-app
          - configMapRef:
              name: cm-database
        ports:
        - containerPort: 3210
          name: app
        - containerPort: 3211
          name: redoc
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3210
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3210
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
