package webhook

import (
	"log"
	"net/http"

	"github.com/thiagoluis88git/tech1/internal/core/domain"
	"github.com/thiagoluis88git/tech1/internal/core/services"
	"github.com/thiagoluis88git/tech1/pkg/environment"
	"github.com/thiagoluis88git/tech1/pkg/httpserver"
)

// @Summary Payment Webhook
// @Description Payment Webhook. This endpoint will be called when the user pays
// @Description the QRCode generated by /api/qrcode/generate [post]
// @Tags Webhook
// @Accept json
// @Produce json
// @Param mercadoLivrePaymentForm body domain.MercadoLivrePaymentForm true "mercadoLivrePaymentForm"
// @Success 204
// @Failure 406 "StatusNotAcceptable - Topic is not 'merchant_order'"
// @Router /api/webhook/ml/payment [post]
func PostMercadoLivreWebhook(mercadoLivreService *services.MercadoLivreService) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var form domain.MercadoLivrePaymentForm

		err := httpserver.DecodeJSONBody(w, r, &form)

		if err != nil {
			log.Print("decoding mercado livre webhook body", map[string]interface{}{
				"error":  err.Error(),
				"status": httpserver.GetStatusCodeFromError(err),
			})
			httpserver.SendBadRequestError(w, err)
			return
		}

		token := environment.GetQRCodeGatewayToken()
		err = mercadoLivreService.FinishOrder(r.Context(), token, form)

		if err != nil {
			log.Print("post mercado livre webhook", map[string]interface{}{
				"error":  err.Error(),
				"status": httpserver.GetStatusCodeFromError(err),
			})
			httpserver.SendResponseError(w, err)
			return
		}

		httpserver.SendResponseNoContentSuccess(w)
	}
}
